version: '3.8'
networks:
  app-tier:
    driver: bridge
services:
  db:
     image: mysql:5.7
     volumes:
        - ./mysql_data:/var/lib/mysql
     restart: always
     networks:
       - app-tier
     environment:
       MYSQL_ROOT_PASSWORD: HbLOA5VZK2aUOiBIfLRl
       MYSQL_DATABASE: dedecms
       MYSQL_USER: dedecms_admin
       MYSQL_PASSWORD: e52njuB3Xz4qgISLBVp4
  phpfpm:
    tty: true #enables debugging capabilities when attached to this container
    build: .
    networks:
      - app-tier
    volumes:
      - ./uploads:/code
  nginx:
    image: 'nginx:1.19.2'
    networks:
      - app-tier
    depends_on:
      - phpfpm
      - db
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./server_block.conf:/etc/nginx/conf.d/default.conf
      - ./uploads:/code
      - ./30_phpfpm_code_chown.sh:/docker-entrypoint.d/20_phpfpm_code_chown.sh
